sonar.projectKey=Orion_Project
sonar.projectName=Orion
sonar.host.url=http://localhost:9000
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
# Exclude test files from coverage & duplications
sonar.exclusions=tests/**

