sonar.projectKey=Orion_Project
sonar.projectName=Orion
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.coverageReportPaths=test-results.xml
# Exclude test files from coverage & duplications
sonar.exclusions=tests/**
