"""
Constants and static mappings for the price target labeler.

Extracted from main_price_target_labeler.py for better modularity.
"""

from datetime import timedelta
from typing import Dict

# -----------------------------------------------------------------------------
# Labeling Configuration
# -----------------------------------------------------------------------------
BATCH_SIZE = 50
POLL_INTERVAL_SECONDS = 60
RISK_FREE_RATE = 0.05  # Risk-free rate for Black-Scholes

# -----------------------------------------------------------------------------
# Checkpoint definitions for price tracking
# Maps checkpoint name to timedelta offset from entry
# -----------------------------------------------------------------------------
CHECKPOINT_OFFSETS: Dict[str, timedelta] = {
    "5m": timedelta(minutes=5),
    "10m": timedelta(minutes=10),
    "15m": timedelta(minutes=15),
    "30m": timedelta(minutes=30),
    "1h": timedelta(hours=1),
    "2h": timedelta(hours=2),
    "4h": timedelta(hours=4),
    "8h": timedelta(hours=8),
    "1d": timedelta(days=1),
    "2d": timedelta(days=2),
    "3d": timedelta(days=3),
    "1w": timedelta(days=7),
    "2w": timedelta(days=14),
    "3w": timedelta(days=21),
    "4w": timedelta(days=28),
}

# -----------------------------------------------------------------------------
# Static sector mapping for reliable feature calculation
# Avoids unreliable API calls for common tickers
# -----------------------------------------------------------------------------
SECTOR_MAPPING: Dict[str, str] = {
    # Technology
    "AAPL": "Technology",
    "MSFT": "Technology",
    "GOOGL": "Technology",
    "GOOG": "Technology",
    "META": "Technology",
    "NVDA": "Technology",
    "AMD": "Technology",
    "INTC": "Technology",
    "CRM": "Technology",
    "ORCL": "Technology",
    "ADBE": "Technology",
    "CSCO": "Technology",
    "AVGO": "Technology",
    "TXN": "Technology",
    "QCOM": "Technology",
    "MU": "Technology",
    "AMAT": "Technology",
    "LRCX": "Technology",
    "KLAC": "Technology",
    "MRVL": "Technology",
    "ON": "Technology",
    "NXPI": "Technology",
    "SMCI": "Technology",
    "ARM": "Technology",
    "DELL": "Technology",
    "HPQ": "Technology",
    "NOW": "Technology",
    "PANW": "Technology",
    "CRWD": "Technology",
    "ZS": "Technology",
    "DDOG": "Technology",
    "SNOW": "Technology",
    "NET": "Technology",
    "MDB": "Technology",
    "PLTR": "Technology",
    "SHOP": "Technology",
    "SQ": "Technology",
    "COIN": "Technology",
    "MSTR": "Technology",
    "SNPS": "Technology",
    "CDNS": "Technology",
    "ASML": "Technology",
    "TSM": "Technology",
    "ANET": "Technology",
    # Consumer Discretionary
    "AMZN": "Consumer Discretionary",
    "TSLA": "Consumer Discretionary",
    "HD": "Consumer Discretionary",
    "NKE": "Consumer Discretionary",
    "LOW": "Consumer Discretionary",
    "SBUX": "Consumer Discretionary",
    "MCD": "Consumer Discretionary",
    "LULU": "Consumer Discretionary",
    "BABA": "Consumer Discretionary",
    "PDD": "Consumer Discretionary",
    "RIVN": "Consumer Discretionary",
    "NIO": "Consumer Discretionary",
    "UBER": "Consumer Discretionary",
    "TGT": "Consumer Discretionary",
    "JD": "Consumer Discretionary",
    "GM": "Consumer Discretionary",
    "F": "Consumer Discretionary",
    "LCID": "Consumer Discretionary",
    # Communication Services
    "NFLX": "Communication Services",
    "DIS": "Communication Services",
    "CMCSA": "Communication Services",
    "T": "Communication Services",
    "VZ": "Communication Services",
    "ROKU": "Communication Services",
    "SPOT": "Communication Services",
    "SNAP": "Communication Services",
    "PINS": "Communication Services",
    "RBLX": "Communication Services",
    # Financial Services
    "JPM": "Financial Services",
    "BAC": "Financial Services",
    "WFC": "Financial Services",
    "C": "Financial Services",
    "GS": "Financial Services",
    "MS": "Financial Services",
    "SCHW": "Financial Services",
    "V": "Financial Services",
    "MA": "Financial Services",
    "PYPL": "Financial Services",
    "AXP": "Financial Services",
    "BLK": "Financial Services",
    "SOFI": "Financial Services",
    "BRKB": "Financial Services",
    "COF": "Financial Services",
    "KKR": "Financial Services",
    "AFRM": "Financial Services",
    # Healthcare
    "UNH": "Healthcare",
    "JNJ": "Healthcare",
    "PFE": "Healthcare",
    "MRK": "Healthcare",
    "ABBV": "Healthcare",
    "LLY": "Healthcare",
    "TMO": "Healthcare",
    "ABT": "Healthcare",
    "NVO": "Healthcare",
    "MRNA": "Healthcare",
    "ISRG": "Healthcare",
    "DXCM": "Healthcare",
    "VRTX": "Healthcare",
    "REGN": "Healthcare",
    "BIIB": "Healthcare",
    "GILD": "Healthcare",
    "AMGN": "Healthcare",
    "DHR": "Healthcare",
    # Energy
    "XOM": "Energy",
    "CVX": "Energy",
    "OXY": "Energy",
    "SLB": "Energy",
    "COP": "Energy",
    "EOG": "Energy",
    "MPC": "Energy",
    "PSX": "Energy",
    "VLO": "Energy",
    "HAL": "Energy",
    # Industrial
    "CAT": "Industrial",
    "DE": "Industrial",
    "UPS": "Industrial",
    "HON": "Industrial",
    "UNP": "Industrial",
    "RTX": "Industrial",
    "LMT": "Industrial",
    "BA": "Industrial",
    "GE": "Industrial",
    # Consumer Staples
    "WMT": "Consumer Staples",
    "COST": "Consumer Staples",
    "PG": "Consumer Staples",
    "KO": "Consumer Staples",
    "PEP": "Consumer Staples",
    "MO": "Consumer Staples",
    "PM": "Consumer Staples",
    "CL": "Consumer Staples",
    "EL": "Consumer Staples",
    # Real Estate
    "AMT": "Real Estate",
    "PLD": "Real Estate",
    "EQIX": "Real Estate",
    "CCI": "Real Estate",
    "O": "Real Estate",
    "SPG": "Real Estate",
    # ETF
    "SPY": "ETF",
    "QQQ": "ETF",
    "IWM": "ETF",
    "DIA": "ETF",
    "XLF": "ETF",
    "XLK": "ETF",
    "XLE": "ETF",
    "XLV": "ETF",
    "XLI": "ETF",
    "XLP": "ETF",
    "XLY": "ETF",
    "XLB": "ETF",
    "XLU": "ETF",
    "XLRE": "ETF",
    "XLC": "ETF",
    "VIXY": "ETF",
    "VXX": "ETF",
    "TLT": "ETF",
    "GLD": "ETF",
    "SLV": "ETF",
    "EEM": "ETF",
    "EWZ": "ETF",
    "FXI": "ETF",
    "ARKK": "ETF",
    "GDX": "ETF",
    "IBIT": "ETF",
    "SQQQ": "ETF",
    "TQQQ": "ETF",
    "SPXU": "ETF",
    "UPRO": "ETF",
    "SMH": "ETF",
    "SOXL": "ETF",
    # Index
    "SPX": "Index",
    "SPXW": "Index",
    "NDX": "Index",
    "RUT": "Index",
    "VIX": "Index",
}
