"""Add BronzeEvent validation fields

Revision ID: 0001_initial_schema_update
Revises:
Create Date: 2025-12-16 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema_update"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column("bronze_events", sa.Column("ticker", sa.String(), nullable=True))
    op.create_index(op.f("idx_bronze_events_ticker"), "bronze_events", ["ticker"], unique=False)
    op.add_column(
        "bronze_events", sa.Column("trading_date", sa.DateTime(timezone=True), nullable=True)
    )  # Nullable first to allow migration if data exists, but strict in model
    op.add_column("bronze_events", sa.Column("session", sa.String(), nullable=True))
    op.add_column("bronze_events", sa.Column("schema_version", sa.String(), nullable=True, server_default="v1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_column("bronze_events", "schema_version")
    op.drop_column("bronze_events", "session")
    op.drop_column("bronze_events", "trading_date")
    op.drop_index(op.f("idx_bronze_events_ticker"), table_name="bronze_events")
    op.drop_column("bronze_events", "ticker")
    # ### end Alembic commands ###
