"""baseline full schema

Revision ID: baseline_2026_06_11
Revises:
Create Date: 2026-06-11 01:33:28.069585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = "baseline_2026_06_11"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before the vector_documents.embedding_vec column is
    # created. Mirrors init_db(), which runs the same statement before
    # Base.metadata.create_all().
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("trace_id", sa.String(), nullable=True),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("client_host", sa.String(), nullable=True),
        sa.Column("query_params", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_log_created_at", "audit_logs", ["created_at_utc"], unique=False)
    op.create_index("ix_audit_log_trace_id", "audit_logs", ["trace_id"], unique=False)
    op.create_table(
        "bronze_events",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_event_id", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("trading_date", sa.Date(), nullable=True),
        sa.Column("session", sa.String(), nullable=False),
        sa.Column("schema_version", sa.String(), nullable=False),
        sa.Column("event_ts_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_ts_utc", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("ingest", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index("idx_bronze_events_source_type", "bronze_events", ["source", "event_type"], unique=False)
    op.create_index("idx_bronze_events_ticker_ts", "bronze_events", ["ticker", "event_ts_utc"], unique=False)
    op.create_index("idx_bronze_events_ts", "bronze_events", ["event_ts_utc"], unique=False)
    op.create_index(op.f("ix_bronze_events_ticker"), "bronze_events", ["ticker"], unique=False)
    op.create_table(
        "candidate_labels",
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("label", sa.Float(), nullable=False),
        sa.Column("ret", sa.Float(), nullable=False),
        sa.Column("barrier_hit_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_to_hit_seconds", sa.Float(), nullable=True),
        sa.Column("mfe", sa.Float(), nullable=True),
        sa.Column("mae", sa.Float(), nullable=True),
        sa.Column("ts_mfe", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ts_mae", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_to_mfe_seconds", sa.Float(), nullable=True),
        sa.Column("time_to_mae_seconds", sa.Float(), nullable=True),
        sa.Column("mfe_mae_ratio", sa.Float(), nullable=True),
        sa.Column("excursion_velocity", sa.Float(), nullable=True),
        sa.Column("capture_efficiency", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    op.create_table(
        "candidate_trades",
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rule_id", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("option_symbol", sa.String(), nullable=True),
        sa.Column("strike_price", sa.Float(), nullable=True),
        sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("option_type", sa.String(), nullable=True),
        sa.Column("underlying_price", sa.Float(), nullable=True),
        sa.Column("premium", sa.Float(), nullable=True),
        sa.Column("execution_params", sa.JSON(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    op.create_index("ix_candidate_option_symbol", "candidate_trades", ["option_symbol"], unique=False)
    op.create_index("ix_candidate_rule", "candidate_trades", ["rule_id"], unique=False)
    op.create_index("ix_candidate_ticker_time", "candidate_trades", ["ticker", "timestamp_utc"], unique=False)
    op.create_index(op.f("ix_candidate_trades_option_symbol"), "candidate_trades", ["option_symbol"], unique=False)
    op.create_index(op.f("ix_candidate_trades_rule_id"), "candidate_trades", ["rule_id"], unique=False)
    op.create_index(op.f("ix_candidate_trades_ticker"), "candidate_trades", ["ticker"], unique=False)
    op.create_index(op.f("ix_candidate_trades_timestamp_utc"), "candidate_trades", ["timestamp_utc"], unique=False)
    op.create_table(
        "dead_letter_queue",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("source_event_id", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=True),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("event_ts_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("trace_id", sa.String(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=False),
        sa.Column("stack_trace", sa.String(), nullable=True),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dead_letter_queue_event_id"), "dead_letter_queue", ["event_id"], unique=False)
    op.create_index(op.f("ix_dead_letter_queue_ticker"), "dead_letter_queue", ["ticker"], unique=False)
    op.create_index("ix_dlq_status_retry", "dead_letter_queue", ["status", "retry_count"], unique=False)
    op.create_table(
        "exit_decisions",
        sa.Column("exit_id", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("candidate_id", sa.String(), nullable=True),
        sa.Column("rule_id", sa.String(), nullable=False),
        sa.Column("exit_reason", sa.String(), nullable=False),
        sa.Column("urgency", sa.String(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("broker_order_id", sa.String(), nullable=True),
        sa.Column("exit_ts_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_price", sa.Float(), nullable=True),
        sa.Column("entry_price", sa.Float(), nullable=True),
        sa.Column("pnl_usd", sa.Float(), nullable=True),
        sa.Column("pnl_pct", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("exit_id"),
    )
    op.create_index("ix_exit_decision_exit_ts", "exit_decisions", ["exit_ts_utc"], unique=False)
    op.create_index(op.f("ix_exit_decisions_candidate_id"), "exit_decisions", ["candidate_id"], unique=False)
    op.create_index(op.f("ix_exit_decisions_ticker"), "exit_decisions", ["ticker"], unique=False)
    op.create_table(
        "fills",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("broker_order_id", sa.String(), nullable=False),
        sa.Column("client_order_id", sa.String(), nullable=True),
        sa.Column("filled_qty", sa.Float(), nullable=False),
        sa.Column("filled_avg_price", sa.Float(), nullable=True),
        sa.Column("side", sa.String(), nullable=True),
        sa.Column("filled_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fills_broker_order_id"), "fills", ["broker_order_id"], unique=False)
    op.create_index(op.f("ix_fills_client_order_id"), "fills", ["client_order_id"], unique=False)
    op.create_index(op.f("ix_fills_ticker"), "fills", ["ticker"], unique=False)
    op.create_index("ux_fills_broker_order_id", "fills", ["broker_order_id"], unique=True)
    op.create_table(
        "gold_feature_events",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("event_ts_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("feature_set_id", sa.String(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("ticker", "event_ts_utc", "feature_set_id"),
    )
    op.create_index("ix_gold_feat_event_ticker_ts", "gold_feature_events", ["ticker", "event_ts_utc"], unique=False)
    op.create_table(
        "gold_ticker_rollup",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("vwap", sa.Float(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("ticker", "period", "timestamp_utc"),
    )
    op.create_index(
        "ix_gold_rollup_ticker_period_ts", "gold_ticker_rollup", ["ticker", "period", "timestamp_utc"], unique=False
    )
    op.create_table(
        "ingest_watermarks",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("last_seen_ts_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_ts_utc", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "job_cursor_state",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("last_seen_ts_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_id", sa.String(), nullable=True),
        sa.Column("updated_ts_utc", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "labels_event",
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("event_ts_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forward_returns", sa.JSON(), nullable=False),
        sa.Column("label", sa.Float(), nullable=True),
        sa.Column("ret", sa.Float(), nullable=True),
        sa.Column("barrier_hit_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_to_hit_seconds", sa.Float(), nullable=True),
        sa.Column("mfe", sa.Float(), nullable=True),
        sa.Column("mae", sa.Float(), nullable=True),
        sa.Column("ts_mfe", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ts_mae", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_to_mfe_seconds", sa.Float(), nullable=True),
        sa.Column("time_to_mae_seconds", sa.Float(), nullable=True),
        sa.Column("mfe_mae_ratio", sa.Float(), nullable=True),
        sa.Column("excursion_velocity", sa.Float(), nullable=True),
        sa.Column("capture_efficiency", sa.Float(), nullable=True),
        sa.Column("label_config", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    op.create_index(op.f("ix_labels_event_event_ts_utc"), "labels_event", ["event_ts_utc"], unique=False)
    op.create_index(op.f("ix_labels_event_ticker"), "labels_event", ["ticker"], unique=False)
    op.create_index("ix_labels_event_ticker_ts", "labels_event", ["ticker", "event_ts_utc"], unique=False)
    op.create_table(
        "labels_window",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("window_end_ts_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("forward_returns", sa.JSON(), nullable=False),
        sa.Column("label_config", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "period", "window_end_ts_utc"),
    )
    op.create_index(
        "ix_labels_window_ticker_period_ts", "labels_window", ["ticker", "period", "window_end_ts_utc"], unique=False
    )
    op.create_table(
        "ml_feature_importance_history",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model_type", sa.String(), nullable=False),
        sa.Column("feature_name", sa.String(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ml_feature_importance_history_feature_name"),
        "ml_feature_importance_history",
        ["feature_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ml_feature_importance_history_model_type"),
        "ml_feature_importance_history",
        ["model_type"],
        unique=False,
    )
    op.create_table(
        "ml_pattern_insights",
        sa.Column("insight_id", sa.String(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model_type", sa.String(), nullable=False),
        sa.Column("model_version", sa.String(), nullable=True),
        sa.Column("training_window_days", sa.Integer(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("positive_rate", sa.Float(), nullable=False),
        sa.Column("train_auc", sa.Float(), nullable=False),
        sa.Column("holdout_auc", sa.Float(), nullable=False),
        sa.Column("precision_at_50", sa.Float(), nullable=True),
        sa.Column("top_rules_json", sa.JSON(), nullable=False),
        sa.Column("top_features_json", sa.JSON(), nullable=False),
        sa.Column("degraded_features_json", sa.JSON(), nullable=True),
        sa.Column("emerging_patterns_json", sa.JSON(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("insight_id"),
    )
    op.create_index(op.f("ix_ml_pattern_insights_model_type"), "ml_pattern_insights", ["model_type"], unique=False)
    op.create_table(
        "ml_predictions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("prediction_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("option_chain", sa.String(), nullable=True),
        sa.Column("bucket", sa.String(), nullable=True),
        sa.Column("model_type", sa.String(), nullable=False),
        sa.Column("prediction_score", sa.Float(), nullable=False),
        sa.Column("prediction_class", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("position_id", sa.String(), nullable=True),
        sa.Column("outcome_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_return_pct", sa.Float(), nullable=True),
        sa.Column("hit_target", sa.Boolean(), nullable=True),
        sa.Column("hit_stop", sa.Boolean(), nullable=True),
        sa.Column("prediction_correct", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ml_predictions_bucket"), "ml_predictions", ["bucket"], unique=False)
    op.create_index(op.f("ix_ml_predictions_model_type"), "ml_predictions", ["model_type"], unique=False)
    op.create_index(op.f("ix_ml_predictions_position_id"), "ml_predictions", ["position_id"], unique=False)
    op.create_index(op.f("ix_ml_predictions_prediction_ts"), "ml_predictions", ["prediction_ts"], unique=False)
    op.create_index(op.f("ix_ml_predictions_symbol"), "ml_predictions", ["symbol"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decision_id", sa.String(), nullable=True),
        sa.Column("candidate_id", sa.String(), nullable=True),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("side", sa.String(), nullable=False),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.Column("limit_price", sa.Float(), nullable=True),
        sa.Column("client_order_id", sa.String(), nullable=True),
        sa.Column("broker_order_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("system", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_broker_order_id"), "orders", ["broker_order_id"], unique=False)
    op.create_index(op.f("ix_orders_candidate_id"), "orders", ["candidate_id"], unique=False)
    op.create_index(op.f("ix_orders_client_order_id"), "orders", ["client_order_id"], unique=False)
    op.create_index(op.f("ix_orders_decision_id"), "orders", ["decision_id"], unique=False)
    op.create_index(op.f("ix_orders_ticker"), "orders", ["ticker"], unique=False)
    op.create_table(
        "pending_orders",
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("signed_cost", sa.Float(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_index(op.f("ix_pending_orders_ticker"), "pending_orders", ["ticker"], unique=False)
    op.create_table(
        "position_running_stats",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("max_return_pct", sa.Float(), nullable=False),
        sa.Column("max_drawdown_pct", sa.Float(), nullable=False),
        sa.Column("last_updated_utc", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "positions_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("snapshot_ts_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("qty", sa.Float(), nullable=False),
        sa.Column("avg_entry_price", sa.Float(), nullable=True),
        sa.Column("market_value", sa.Float(), nullable=True),
        sa.Column("unrealized_pl", sa.Float(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_positions_snapshots_snapshot_ts_utc"), "positions_snapshots", ["snapshot_ts_utc"], unique=False
    )
    op.create_index(op.f("ix_positions_snapshots_ticker"), "positions_snapshots", ["ticker"], unique=False)
    op.create_index(
        "ix_positions_snapshots_ts_ticker", "positions_snapshots", ["snapshot_ts_utc", "ticker"], unique=False
    )
    op.create_table(
        "processed_fills",
        sa.Column("fill_id", sa.String(), nullable=False),
        sa.Column("client_order_id", sa.String(), nullable=True),
        sa.Column("processed_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("qty", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("fill_id"),
    )
    op.create_index(op.f("ix_processed_fills_client_order_id"), "processed_fills", ["client_order_id"], unique=False)
    op.create_table(
        "regime_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("trend_regime", sa.String(length=20), nullable=True),
        sa.Column("vol_regime", sa.String(length=20), nullable=True),
        sa.Column("risk_regime", sa.String(length=20), nullable=True),
        sa.Column("session_regime", sa.String(length=20), nullable=True),
        sa.Column("vix_regime", sa.String(length=20), nullable=True),
        sa.Column("vix_level", sa.Float(), nullable=True),
        sa.Column("realized_vol", sa.Float(), nullable=True),
        sa.Column("trend_strength", sa.Float(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("confidence_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_regime_snapshots_ticker_ts", "regime_snapshots", ["ticker", "ts_utc"], unique=False)
    op.create_index(op.f("ix_regime_snapshots_ticker"), "regime_snapshots", ["ticker"], unique=False)
    op.create_index(op.f("ix_regime_snapshots_ts_utc"), "regime_snapshots", ["ts_utc"], unique=False)
    op.create_table(
        "risk_state",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_daily_loss", sa.Float(), nullable=True),
        sa.Column("current_equity", sa.Float(), nullable=True),
        sa.Column("starting_equity", sa.Float(), nullable=True),
        sa.Column("peak_equity", sa.Float(), nullable=True),
        sa.Column("open_positions_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtime_config",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("updated_ts_utc", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "signals_live",
        sa.Column("signal_id", sa.String(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("rule_id", sa.String(), nullable=True),
        sa.Column("model_version", sa.String(), nullable=True),
        sa.Column("expected_return", sa.Float(), nullable=True),
        sa.Column("p_take", sa.Float(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("entry_logic", sa.JSON(), nullable=False),
        sa.Column("exit_rules", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("decision_trace_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("signal_id"),
    )
    op.create_index(op.f("ix_signals_live_model_version"), "signals_live", ["model_version"], unique=False)
    op.create_index(op.f("ix_signals_live_rule_id"), "signals_live", ["rule_id"], unique=False)
    op.create_index(op.f("ix_signals_live_ticker"), "signals_live", ["ticker"], unique=False)
    op.create_index("ix_signals_live_ticker_time", "signals_live", ["ticker", "timestamp_utc"], unique=False)
    op.create_index(op.f("ix_signals_live_timestamp_utc"), "signals_live", ["timestamp_utc"], unique=False)
    op.create_table(
        "silver_signals",
        sa.Column("signal_id", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("signal_ts_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("signal_type", sa.String(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("signal_id"),
    )
    op.create_index(op.f("ix_silver_signals_signal_ts_utc"), "silver_signals", ["signal_ts_utc"], unique=False)
    op.create_index(op.f("ix_silver_signals_ticker"), "silver_signals", ["ticker"], unique=False)
    op.create_index("ix_silver_ticker_time", "silver_signals", ["ticker", "signal_ts_utc"], unique=False)
    op.create_table(
        "solvers",
        sa.Column("solver_id", sa.String(), nullable=False),
        sa.Column("family_name", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("parent_solver_id", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("definition_json", sa.JSON(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("total_pnl", sa.Float(), nullable=False),
        sa.Column("sharpe_ratio", sa.Float(), nullable=False),
        sa.Column("win_rate", sa.Float(), nullable=False),
        sa.Column("trades_count", sa.Integer(), nullable=False),
        sa.Column("info_ratio", sa.Float(), nullable=False),
        sa.Column("profit_factor", sa.Float(), nullable=False),
        sa.Column("max_dd_pct", sa.Float(), nullable=False),
        sa.Column("stability_score", sa.Float(), nullable=False),
        sa.Column("oos_expect_bp", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_solver_id"],
            ["solvers.solver_id"],
        ),
        sa.PrimaryKeyConstraint("solver_id"),
    )
    op.create_index("ix_solver_active_stage", "solvers", ["is_active", "stage"], unique=False)
    op.create_table(
        "strategy_decisions",
        sa.Column("decision_id", sa.String(), nullable=False),
        sa.Column("candidate_id", sa.String(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("strategy_version_id", sa.String(), nullable=False),
        sa.Column("model_version", sa.String(), nullable=True),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("p_take", sa.Float(), nullable=True),
        sa.Column("execution_params", sa.JSON(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("executed_successfully", sa.String(), nullable=True),
        sa.Column("decision_trace_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_index("ix_strategy_decision_ticker_ts", "strategy_decisions", ["ticker", "timestamp_utc"], unique=False)
    op.create_index(op.f("ix_strategy_decisions_candidate_id"), "strategy_decisions", ["candidate_id"], unique=False)
    op.create_table(
        "system_status",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("last_updated_utc", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("details", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "trade_journal_entries",
        sa.Column("decision_id", sa.String(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("signal_id", sa.String(), nullable=False),
        sa.Column("candidate_id", sa.String(), nullable=True),
        sa.Column("solver_id", sa.String(), nullable=True),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("decision_trace_json", sa.JSON(), nullable=False),
        sa.Column("client_order_id", sa.String(), nullable=True),
        sa.Column("broker_order_id", sa.String(), nullable=True),
        sa.Column("filled_qty", sa.Float(), nullable=True),
        sa.Column("filled_avg_price", sa.Float(), nullable=True),
        sa.Column("filled_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("realized_pnl", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_index(
        op.f("ix_trade_journal_entries_broker_order_id"), "trade_journal_entries", ["broker_order_id"], unique=False
    )
    op.create_index(
        op.f("ix_trade_journal_entries_candidate_id"), "trade_journal_entries", ["candidate_id"], unique=False
    )
    op.create_index(
        op.f("ix_trade_journal_entries_client_order_id"), "trade_journal_entries", ["client_order_id"], unique=False
    )
    op.create_index(op.f("ix_trade_journal_entries_signal_id"), "trade_journal_entries", ["signal_id"], unique=False)
    op.create_index(op.f("ix_trade_journal_entries_solver_id"), "trade_journal_entries", ["solver_id"], unique=False)
    op.create_index(op.f("ix_trade_journal_entries_ticker"), "trade_journal_entries", ["ticker"], unique=False)
    op.create_index(
        "ix_trade_journal_ticker_created", "trade_journal_entries", ["ticker", "created_at_utc"], unique=False
    )
    op.create_table(
        "vector_documents",
        sa.Column("doc_id", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=False),
        sa.Column("embedding_vec", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("doc_id"),
    )
    op.create_table(
        "meta_experiments",
        sa.Column("experiment_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("start_time_utc", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("end_time_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trial_count", sa.Integer(), nullable=False),
        sa.Column("best_solver_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("objective", sa.String(), nullable=True),
        sa.Column("base_solver_ids", sa.JSON(), nullable=True),
        sa.Column("config_json", sa.JSON(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["best_solver_id"],
            ["solvers.solver_id"],
        ),
        sa.PrimaryKeyConstraint("experiment_id"),
    )
    op.create_table(
        "promotion_recommendations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("solver_id", sa.String(), nullable=False),
        sa.Column("current_stage", sa.String(), nullable=False),
        sa.Column("recommended_stage", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("metrics_snapshot", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("reviewed_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["solver_id"],
            ["solvers.solver_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "solver_metrics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("solver_id", sa.String(), nullable=False),
        sa.Column("sector", sa.String(), nullable=False),
        sa.Column("ticker_bucket", sa.String(), nullable=True),
        sa.Column("horizon_profile", sa.String(), nullable=True),
        sa.Column("dataset_tag", sa.String(), nullable=False),
        sa.Column("num_runs", sa.Integer(), nullable=False),
        sa.Column("num_trades", sa.Integer(), nullable=False),
        sa.Column("sharpe_ratio", sa.Float(), nullable=False),
        sa.Column("info_ratio", sa.Float(), nullable=False),
        sa.Column("profit_factor", sa.Float(), nullable=False),
        sa.Column("oos_expect_bp", sa.Float(), nullable=True),
        sa.Column("max_dd_pct", sa.Float(), nullable=False),
        sa.Column("stability_score", sa.Float(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("evaluated_at_utc", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["solver_id"],
            ["solvers.solver_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_solver_metrics_solver_id"), "solver_metrics", ["solver_id"], unique=False)
    op.create_table(
        "solver_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("solver_id", sa.String(), nullable=False),
        sa.Column("dataset_tag", sa.String(), nullable=False),
        sa.Column("time_window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("num_candidates", sa.Integer(), nullable=False),
        sa.Column("num_trades", sa.Integer(), nullable=False),
        sa.Column("gross_pnl", sa.Float(), nullable=True),
        sa.Column("net_pnl", sa.Float(), nullable=True),
        sa.Column("profit_factor", sa.Float(), nullable=True),
        sa.Column("max_drawdown_pct", sa.Float(), nullable=True),
        sa.Column("expect_return_bp", sa.Float(), nullable=True),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["solver_id"],
            ["solvers.solver_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_solver_runs_solver_id"), "solver_runs", ["solver_id"], unique=False)
    op.create_table(
        "solver_edits",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("experiment_id", sa.String(), nullable=True),
        sa.Column("base_solver_id", sa.String(), nullable=False),
        sa.Column("new_solver_id", sa.String(), nullable=False),
        sa.Column("edit_json", sa.JSON(), nullable=False),
        sa.Column("generated_by", sa.String(), nullable=False),
        sa.Column("reward", sa.Float(), nullable=True),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("evaluated_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_solver_id"],
            ["solvers.solver_id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["meta_experiments.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["new_solver_id"],
            ["solvers.solver_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("solver_edits")
    op.drop_index(op.f("ix_solver_runs_solver_id"), table_name="solver_runs")
    op.drop_table("solver_runs")
    op.drop_index(op.f("ix_solver_metrics_solver_id"), table_name="solver_metrics")
    op.drop_table("solver_metrics")
    op.drop_table("promotion_recommendations")
    op.drop_table("meta_experiments")
    op.drop_table("vector_documents")
    op.drop_index("ix_trade_journal_ticker_created", table_name="trade_journal_entries")
    op.drop_index(op.f("ix_trade_journal_entries_ticker"), table_name="trade_journal_entries")
    op.drop_index(op.f("ix_trade_journal_entries_solver_id"), table_name="trade_journal_entries")
    op.drop_index(op.f("ix_trade_journal_entries_signal_id"), table_name="trade_journal_entries")
    op.drop_index(op.f("ix_trade_journal_entries_client_order_id"), table_name="trade_journal_entries")
    op.drop_index(op.f("ix_trade_journal_entries_candidate_id"), table_name="trade_journal_entries")
    op.drop_index(op.f("ix_trade_journal_entries_broker_order_id"), table_name="trade_journal_entries")
    op.drop_table("trade_journal_entries")
    op.drop_table("system_status")
    op.drop_index(op.f("ix_strategy_decisions_candidate_id"), table_name="strategy_decisions")
    op.drop_index("ix_strategy_decision_ticker_ts", table_name="strategy_decisions")
    op.drop_table("strategy_decisions")
    op.drop_index("ix_solver_active_stage", table_name="solvers")
    op.drop_table("solvers")
    op.drop_index("ix_silver_ticker_time", table_name="silver_signals")
    op.drop_index(op.f("ix_silver_signals_ticker"), table_name="silver_signals")
    op.drop_index(op.f("ix_silver_signals_signal_ts_utc"), table_name="silver_signals")
    op.drop_table("silver_signals")
    op.drop_index(op.f("ix_signals_live_timestamp_utc"), table_name="signals_live")
    op.drop_index("ix_signals_live_ticker_time", table_name="signals_live")
    op.drop_index(op.f("ix_signals_live_ticker"), table_name="signals_live")
    op.drop_index(op.f("ix_signals_live_rule_id"), table_name="signals_live")
    op.drop_index(op.f("ix_signals_live_model_version"), table_name="signals_live")
    op.drop_table("signals_live")
    op.drop_table("runtime_config")
    op.drop_table("risk_state")
    op.drop_index(op.f("ix_regime_snapshots_ts_utc"), table_name="regime_snapshots")
    op.drop_index(op.f("ix_regime_snapshots_ticker"), table_name="regime_snapshots")
    op.drop_index("idx_regime_snapshots_ticker_ts", table_name="regime_snapshots")
    op.drop_table("regime_snapshots")
    op.drop_index(op.f("ix_processed_fills_client_order_id"), table_name="processed_fills")
    op.drop_table("processed_fills")
    op.drop_index("ix_positions_snapshots_ts_ticker", table_name="positions_snapshots")
    op.drop_index(op.f("ix_positions_snapshots_ticker"), table_name="positions_snapshots")
    op.drop_index(op.f("ix_positions_snapshots_snapshot_ts_utc"), table_name="positions_snapshots")
    op.drop_table("positions_snapshots")
    op.drop_table("position_running_stats")
    op.drop_index(op.f("ix_pending_orders_ticker"), table_name="pending_orders")
    op.drop_table("pending_orders")
    op.drop_index(op.f("ix_orders_ticker"), table_name="orders")
    op.drop_index(op.f("ix_orders_decision_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_client_order_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_candidate_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_broker_order_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_ml_predictions_symbol"), table_name="ml_predictions")
    op.drop_index(op.f("ix_ml_predictions_prediction_ts"), table_name="ml_predictions")
    op.drop_index(op.f("ix_ml_predictions_position_id"), table_name="ml_predictions")
    op.drop_index(op.f("ix_ml_predictions_model_type"), table_name="ml_predictions")
    op.drop_index(op.f("ix_ml_predictions_bucket"), table_name="ml_predictions")
    op.drop_table("ml_predictions")
    op.drop_index(op.f("ix_ml_pattern_insights_model_type"), table_name="ml_pattern_insights")
    op.drop_table("ml_pattern_insights")
    op.drop_index(op.f("ix_ml_feature_importance_history_model_type"), table_name="ml_feature_importance_history")
    op.drop_index(op.f("ix_ml_feature_importance_history_feature_name"), table_name="ml_feature_importance_history")
    op.drop_table("ml_feature_importance_history")
    op.drop_index("ix_labels_window_ticker_period_ts", table_name="labels_window")
    op.drop_table("labels_window")
    op.drop_index("ix_labels_event_ticker_ts", table_name="labels_event")
    op.drop_index(op.f("ix_labels_event_ticker"), table_name="labels_event")
    op.drop_index(op.f("ix_labels_event_event_ts_utc"), table_name="labels_event")
    op.drop_table("labels_event")
    op.drop_table("job_cursor_state")
    op.drop_table("ingest_watermarks")
    op.drop_index("ix_gold_rollup_ticker_period_ts", table_name="gold_ticker_rollup")
    op.drop_table("gold_ticker_rollup")
    op.drop_index("ix_gold_feat_event_ticker_ts", table_name="gold_feature_events")
    op.drop_table("gold_feature_events")
    op.drop_index("ux_fills_broker_order_id", table_name="fills")
    op.drop_index(op.f("ix_fills_ticker"), table_name="fills")
    op.drop_index(op.f("ix_fills_client_order_id"), table_name="fills")
    op.drop_index(op.f("ix_fills_broker_order_id"), table_name="fills")
    op.drop_table("fills")
    op.drop_index(op.f("ix_exit_decisions_ticker"), table_name="exit_decisions")
    op.drop_index(op.f("ix_exit_decisions_candidate_id"), table_name="exit_decisions")
    op.drop_index("ix_exit_decision_exit_ts", table_name="exit_decisions")
    op.drop_table("exit_decisions")
    op.drop_index("ix_dlq_status_retry", table_name="dead_letter_queue")
    op.drop_index(op.f("ix_dead_letter_queue_ticker"), table_name="dead_letter_queue")
    op.drop_index(op.f("ix_dead_letter_queue_event_id"), table_name="dead_letter_queue")
    op.drop_table("dead_letter_queue")
    op.drop_index(op.f("ix_candidate_trades_timestamp_utc"), table_name="candidate_trades")
    op.drop_index(op.f("ix_candidate_trades_ticker"), table_name="candidate_trades")
    op.drop_index(op.f("ix_candidate_trades_rule_id"), table_name="candidate_trades")
    op.drop_index(op.f("ix_candidate_trades_option_symbol"), table_name="candidate_trades")
    op.drop_index("ix_candidate_ticker_time", table_name="candidate_trades")
    op.drop_index("ix_candidate_rule", table_name="candidate_trades")
    op.drop_index("ix_candidate_option_symbol", table_name="candidate_trades")
    op.drop_table("candidate_trades")
    op.drop_table("candidate_labels")
    op.drop_index(op.f("ix_bronze_events_ticker"), table_name="bronze_events")
    op.drop_index("idx_bronze_events_ts", table_name="bronze_events")
    op.drop_index("idx_bronze_events_ticker_ts", table_name="bronze_events")
    op.drop_index("idx_bronze_events_source_type", table_name="bronze_events")
    op.drop_table("bronze_events")
    op.drop_index("ix_audit_log_trace_id", table_name="audit_logs")
    op.drop_index("ix_audit_log_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
